config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users

  resources :groups do
    resources :memberships
    resources :exchanges, only: %i[ create show ]
  end

  get "about" => "pages#about"
end

app/models/group.rb
class Group < ApplicationRecord
  include Invitable

  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :exchanges, dependent: :destroy
  belongs_to :creator, class_name: 'User'

  after_create_commit :set_admin

  def admins
    memberships.where(admin: true)
  end

  def can_draw_names?
    !names_drawn? && memberships.count > 2 && all_members_confirmed?
  end

  def draw_names
    Draw.new(self).perform
  end

  def receiver_for(giver)
    exchanges.find_by giver: giver.membership(self)
  end

  def notify_admins_if_ready_to_draw
    if can_draw_names?
      admins.each do |admin|
        GroupMailer.ready_to_draw(self, admin.user).deliver
      end
    end
  end

  private
    def set_admin
      memberships.find_by(user: creator).update! admin: true, confirmed: true
    end

    def all_members_confirmed?
      memberships.where(confirmed: false).none?
    end
end

app/models/group/invitable.rb
module Group::Invitable
  def invite(email_address_params)
    parsed(email_address_params).each do |email_address|
      add_to_group(email_address)
    end
  end

  private
    def find_or_invite_user(email_address)
      User.find_by(email: email_address) || User.invite!(email: email_address)
    end

    def add_to_group(email_address)
      transaction do
        user = find_or_invite_user(email_address)
        memberships.create! user: user
        send_invitation_email(user)
      end
    end

    def send_invitation_email(user)
      GroupMailer.invited_to_group(self, user).deliver
    end

    def parsed(email_address_params)
      (email_address_list(email_address_params) | contact_list(email_address_params)).uniq
    end

    def email_address_list(email_address_params)
      email_address_params[:email_addresses].split(',').map { |email| email.split(' ') }.flatten
    end

    def contact_list(email_address_params)
      email_address_params[:contact_email_addresses].to_h.map { |email_address, present| email_address if present.to_i.positive? }.compact
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]
  before_action :check_admin, only: %i[ edit update destroy ]

  def index
    @groups = current_user.groups
  end

  def new
  end

  def show
    @membership = current_user.membership(@group)
    @exchange   = @group.receiver_for(current_user)
  end

  def create
    group = current_user.groups.create! group_params.merge(creator: current_user)
    redirect_to group
  end

  def edit
  end

  def update
    @group.update! group_params
    redirect_to @group, notice: "Group successfully updated."
  end

  def destroy
    @group.destroy!
    redirect_to groups_url, notice: "Group successfully destroyed."
  end

  private
    def set_group
      @group = current_user.groups.find params[:id]
    end

    def check_admin
      redirect_to @group, alert: "Only admins can edit the group." unless current_user.admin?(@group)
    end

    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/views/groups/_form.html.erb
<%= form_with model: group do |form| %>
  <p>
    <%= form.label :name, "Name:" %>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :description, "Description:" %>
    <%= form.text_area :description %>
  </p>

  <p><%= form.submit "Save" %></p>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit <%= @group.name %></h1>

<div class="menu">
  <%= link_to "« Back to group", group_path(@group) %>
</div>

<div class="box">
  <%= render 'form', group: @group %>
</div>

app/views/groups/index.html.erb
<h1>My Groups</h1>

<div class="menu">
  <%= link_to "New group", new_group_path %>
</div>

<% if @groups.any? %>
  <% @groups.each do |group| %>
    <div class="box">
      <%= link_to group.name, group_path(group) %>

      <p><%= group.description %></p>
    </div>
  <% end %>
<% else %>
  <p>You don't have any groups yet!</p>
<% end %>

app/views/groups/new.html.erb
<h1>Create group</h1>

<div class="menu">
  <%= link_to "« Back to groups", groups_path %>
</div>

<div class="box">
  <%= render 'form', group: Group.new %>
</div>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>

<% unless @membership.confirmed? %>
  <div class="confirmation-box">
    <span>You've been invited to join this group.</span>

    <%= form_with model: @membership, url: group_membership_path(@group, @membership), method: :put do |form| %>
      <%= form.hidden_field :confirmed, value: true %>
      <%= form.submit "Accept invitation" %>
    <% end %>
  </div>
<% end %>

<div class="menu">
  <% if current_user.admin?(@group) %>
    <%= link_to "Edit group", edit_group_path(@group) %>
  <% end %>

  <%= link_to "My wishlist", edit_group_membership_path(@group, current_user.membership(@group)) %>

  <% unless @group.names_drawn? %>
    <%= link_to "Invite people", new_group_membership_path(@group) %>

    <% unless current_user.admin?(@group) %>
      <%= link_to "Leave group", group_membership_path(@group, current_user.membership(@group)), method: :delete %>
    <% end %>
  <% end %>

  <% if current_user.admin?(@group) && @group.can_draw_names? %>
    <%= button_to "Draw names!", group_exchanges_path(@group), method: :post %>
  <% end %>

  <% if @exchange %>
    <%= button_to "Who did I get?", group_exchange_path(@group, @exchange), method: :get %>
  <% end %>
</div>

<div class="box">
  <div class="box-header">
    <p class="title">Description</p>
  </div>

  <p><%= @group.description %></p>
</div>

<div class="box">
  <div class="box-header">
    <p class="title">Members</p>

    <% if current_user.admin?(@group) && !@group.names_drawn? %>
      <div class="box-menu">
        <%= link_to "Edit", group_memberships_path(@group) %>
      </div>
    <% end %>
  </div>


  <div class="members">
    <% @group.memberships.each do |member| %>
      <%= link_to group_membership_path(@group, member) do %>
        <div class="member">
          <%= display_avatar(member.user) %>

          <span><%= member.name %></span>

          <%= render "memberships/status", member: member %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="box">
  <div class="box-header">
    <p class="title">Status</p>
  </div>

  <% if @group.names_drawn? %>
    <p>
      Names have been drawn!
      <%= link_to "Check out who you got", group_exchange_path(@group, @exchange) %>.
    </p>
  <% else %>
    Draw pending. Names can only be drawn once the group has more than 2 members and all of them are confirmed. Admins will be notified when names are ready to be drawn.
  <% end %>
</div>